import type { Metadata } from "next";
import { Unbounded, Bebas_Neue } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/Header/Header";
import { SmoothScroll } from "@/components/ui/SmoothScroll/SmoothScroll";
import { SiteGsapAnimations } from "@/components/ui/SiteGsapAnimations";
import ScrollTop from "@/components/ui/ScrollTop";

const bebasNeue = Bebas_Neue({
  variable: "--font-bebas-neue",
  weight: ["400"],
  subsets: ["latin"],
});

const unbounded = Unbounded({
  variable: "--font-unbounded",
  weight: ["400", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${bebasNeue.variable} ${unbounded.variable}`}>
      <body className="">
        <SmoothScroll>
          <SiteGsapAnimations />
          <Header />
          <main>{children}</main>
          <ScrollTop />
        </SmoothScroll>
      </body>
    </html>
  );
}
